# DELETE http://localhost:3001/api/blogs/5f66e3aa2e20610af089e54d
DELETE http://localhost:3001/api/blogs/5f8a4ce308346d30b4a696f0
Authorization: bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6InJvb3QiLCJpZCI6IjVmNjZmNWExZDJkNmIyMjUzODJkMWQwNiIsImlhdCI6MTYwMjg5ODMwMX0.UBStm2x1lx3krd_MajMYGhTHmV7OUUnpu8wYi2OkzXo
