# DELETE http://localhost:3001/api/blogs/5f66e3aa2e20610af089e54d
DELETE http://localhost:3001/api/blogs/5f66ba55619a031de01e314a
Authorization: bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6Ikg0MjM1MjN0cnlyNDYzIiwiaWQiOiI1ZjY2YjgyNWI5NWFjNTMwYzA4ZDM0ODciLCJpYXQiOjE2MDA1Njk4MzZ9.WDnn8H1YzBy0OI1LDjP1KlDN3Z5t3Dja7KAwAgj9V2A
